image: node:16.15.1


stages:
  - test          
  - deploy

#workflow:
#  rules:
#    - if: '$CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "develop" || "main" && $CI_COMMIT_REF_NAME == "feature" || "release" && $CI_PIPELINE_SOURCE == "merge_request_event"'
#    - if: $CI_MERGE_REQUEST_APPROVED



before_script:
  - apt-get update && apt-get install --yes libgtk2.0-0 libgtk-3-0 libgbm-dev libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2 libxtst6 xauth xvfb
  - echo "CLIENT_ID"=$CLIENT_ID >> .env 
  - echo "TENANT_ID"=$TENANT_ID >> .env  
  - echo "CLIENT_SECRET"=$CLIENT_SECRET >> .env 
  - echo "REDIRECT_ROUTE"=$REDIRECT_ROUTE >> .env   
  - echo "AUTHORITY"=$AUTHORITY >> .env
  - echo "REDIRECT_ROUTE"=$REDIRECT_ROUTE >> .env
  - echo $user_auth >> cypress.env.json  
  - yarn install
  - yarn run init:serv



e2e-test-job:
  stage: test
  script:
    - yarn run cy:run



deploy-job:       # This job runs in the build stage, which runs first.
  stage: deploy
  rules:
    - if: '$CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "main" && $CI_COMMIT_REF_NAME == "release" && $CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: $CI_MERGE_REQUEST_APPROVED
  script:
    - echo "Compiling the code..."
    - echo "Compile complete."
    - node --version
  when: on_success

