image: node:16.5.1


stages:
  - test          
  - deploy

#workflow:
#  rules:
#    - if: '$CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "develop" || "main" && $CI_COMMIT_REF_NAME == "feature" || "release" && $CI_PIPELINE_SOURCE == "merge_request_event"'
#    - if: $CI_MERGE_REQUEST_APPROVED



variables:
  CLIENT_ID: $CLIENT_ID
  TENANT_ID: $TENANT_ID
  CLIENT_SECRET: $CLIENT_SECRET
  REDIRECT_ROUTE: $REDIRECT_ROUTE
  AUTHORITY: $AUTHORITY
  CONTAINER_TEST_IMAGE: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
  CONTAINER_RELEASE_IMAGE: $CI_REGISTRY_IMAGE:latest
  USER: $USER
  PASSWORD: $PASSWORD


before_script:
  - apt-get update && apt-get install --yes libgtk2.0-0 libgtk-3-0 libgbm-dev libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2 libxtst6 xauth xvfb
  - yarn install
  - yarn run init:serv



e2e-test-job:
  stage: test
  script:
    - yarn run cy:run



deploy-job:       # This job runs in the build stage, which runs first.
  stage: deploy
  rules:
    - if: '$CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "main" && $CI_COMMIT_REF_NAME == "release" && $CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: $CI_MERGE_REQUEST_APPROVED
  script:
    - echo "Compiling the code..."
    - echo "Compile complete."
    - node --version
  when: on_success

