image: docker:19.03.12
services:
  - docker:19.03.12-dind


stages:
  - build
  - test          
  - deploy

#workflow:
#  rules:
#    - if: '$CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "develop" || "main" && $CI_COMMIT_REF_NAME == "feature" || "release" && $CI_PIPELINE_SOURCE == "merge_request_event"'
#    - if: $CI_MERGE_REQUEST_APPROVED



variables:
  CLIENT_ID: $CLIENT_ID
  TENANT_ID: $TENANT_ID
  CLIENT_SECRET: $CLIENT_SECRET
  REDIRECT_ROUTE: $REDIRECT_ROUTE
  AUTHORITY: $AUTHORITY
  CONTAINER_TEST_IMAGE: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
  CONTAINER_RELEASE_IMAGE: $CI_REGISTRY_IMAGE:latest
  USER: $USER
  PASSWORD: $PASSWORD


before_script:
  - npm install --global yarn
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY


build-job:       # This job runs in the build stage, which runs first.
  stage: build
  script:
    - docker build -t $CONTAINER_TEST_IMAGE .
    - docker push $CONTAINER_TEST_IMAGE
  


e2e-test-job:
  stage: test
  script:
    - docker pull $CONTAINER_TEST_IMAGE
    - docker run -d -p 4000:4000 $CONTAINER_TEST_IMAGE
    - yarn run cy:run


deploy-job:       # This job runs in the build stage, which runs first.
  stage: deploy
  rules:
    - if: '$CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "main" && $CI_COMMIT_REF_NAME == "release" && $CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: $CI_MERGE_REQUEST_APPROVED
  script:
    - echo "Compiling the code..."
    - echo "Compile complete."
    - node --version
  when: on_success

