image: docker/compose:latest
services:
  - name: docker:dind
    alias: thedockerhost

variables:
  DOCKER_HOST: tcp://thedockerhost:2375/
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""


stages:
  - build
  - test          
  - deploy



before_script:
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY


#workflow:
#  rules:
#    - if: '$CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "develop" || "main" && $CI_COMMIT_REF_NAME == "feature" || "release" && $CI_PIPELINE_SOURCE == "merge_request_event"'
#    - if: $CI_MERGE_REQUEST_APPROVED


build-job:       # This job runs in the build stage, which runs first.
  stage: build
  script:
    - echo SERVER_PORT=$SERVER_PORT >> .env
    - echo APP_CLIENT_ID=$APP_CLIENT_ID >> .env
    - echo SESSION_SECRET=$SESSION_SECRET >> .env
    - echo APP_CLIENT_SECRET=$APP_CLIENT_SECRET >> .env
    - echo SIGN_UP_SIGN_IN_POLICY_AUTHORITY=$SIGN_UP_SIGN_IN_POLICY_AUTHORITY >> .env
    - echo RESET_PASSWORD_POLICY_AUTHORITY=$RESET_PASSWORD_POLICY_AUTHORITY >> .env
    - echo AUTHORITY_DOMAIN=$AUTHORITY_DOMAIN >> .env
    - echo APP_REDIRECT_URI=$APP_REDIRECT_URI >> .env
    - echo LOGOUT_ENDPOINT=$LOGOUT_ENDPOINT >> .env
    - cd e2e && echo USER_TEST_IGUA=$USER >> .env
    - echo PASSWORD_TEST_IGUA=$PASSWORD_TEST_IGUA >> .env $$ cd ..
    - apk add --no-cache bash python3
    - docker-compose build
    - docker-compose push



e2e-test-job:
  stage: test
  script:
    - docker-compose pull
    - docker-compose up --abort-on-container-exit --exit-code-from e2e
  artifacts:
    when: always
    paths:
      - e2e/cypress/videos/**/*.mp4
      - e2e/cypress/screenshots/**/*.png
    expire_in: 1 day



deploy-job:       # This job runs in the build stage, which runs first.
  stage: deploy
  rules:
    - if: '$CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "main" && $CI_COMMIT_REF_NAME == "release" && $CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: $CI_MERGE_REQUEST_APPROVED
  script:
    - echo "Compiling the code..."
    - echo "Compile complete."
  when: on_success

