version: '3'
services:
  web:
    image: web
    build: ./
    container_name: web
    ports:
      - "4000:4000"

  e2e:
    image: cypress/included:3.2.0
    depends_on:
      - web
    # note: inside e2e container, the network allows accessing
    # "web" host under name "web"
    # so "curl http://web" would return whatever the webserver
    # in the "web" container is cooking
    # see https://docs.docker.com/compose/networking/
    command: yarn cypress run
   
