const swaggerAutogen = require('swagger-autogen');

const outputFile = './web/swagger_output.json';
const endpointsFiles = ['./web/src/api/app.js'];

const doc = {
  info: {
    version: '1.0.0',
    title: 'Igua Auth',
    description: 'Documentation automatically generated by the <b>swagger-autogen</b> module.',
  },
  host: 'localhost:4000',
  basePath: '/',
  schemes: ['http', 'https'],
  consumes: ['application/json'],
  produces: ['application/json'],
  tags: [
    {
      name: 'User',
      description: 'Endpoints',
    },
  ],
  securityDefinitions: {
    apiKeyAuth: {
      type: 'apiKey',
      in: 'header', // can be "header", "query" or "cookie"
      name: 'X-API-KEY', // name of the header, query parameter or cookie
      description: 'any description...',
    },
  },
  definitions: {
    AddUser: {
      type: 'object',
      properties: {
        accountEnabled: true,
        city: 'Seattle',
        country: 'United States',
        department: 'Sales & Marketing',
        displayName: 'Melissa Darrow',
        givenName: 'Melissa',
        jobTitle: 'Marketing Director',
        mailNickname: 'MelissaD',
        passwordPolicies: 'DisablePasswordExpiration',
        passwordProfile: {
          password: 'Ch@angeme!',
          forceChangePasswordNextSignIn: false,
        },
        officeLocation: '131/1105',
        postalCode: '98052',
        preferredLanguage: 'en-US',
        state: 'WA',
        streetAddress: '9256 Towne Center Dr., Suite 400',
        surname: 'Darrow',
        mobilePhone: '+1 206 555 0110',
        usageLocation: 'US',
        identities: [
          {
            signinType: 'userName',
            issuer: 'iguateste.onmicrosoft.com',
            issuerAssignedId: '07027495910',
          },
        ],
      },
    },
    User: {
      type: 'object',
      properties: {
        '@odata.context': 'https://graph.microsoft.com/v1.0/$metadata#users/$entity',
        displayName: 'Daniel Kohntopp',
        surname: 'Kohntopp',
        givenName: 'Daniel',
        id: 'b158284aebf426bf',
        userPrincipalName: 'danielkohntopp@gmail.com',
        businessPhones: ['732-555-0110'],
        jobTitle: 'Software Engineer',
        mail: 'daniel@gmail.com',
        mobilePhone: '+1 206 555 0110',
        officeLocation: '131/1105',
        preferredLanguage: 'pt-BR',
      },
    },
    Users: {
      type: 'object',
      properties: {
        '@odata.context': 'https://graph.microsoft.com/v1.0/$metadata#users',
        value: [
          {
            displayName: 'Daniel Kohntopp',
            surname: 'Kohntopp',
            givenName: 'Daniel',
            id: 'b158284aebf426bf',
            userPrincipalName: 'danielkohntopp@gmail.com',
            businessPhones: ['732-555-0110'],
            jobTitle: 'Software Engineer',
            mail: 'daniel@gmail.com',
            mobilePhone: '+1 206 555 0110',
            officeLocation: '131/1105',
            preferredLanguage: 'pt-BR',
          },
        ],
      },
    },
  },
};

swaggerAutogen()(outputFile, endpointsFiles, doc);
